version: '3.4'

services:
  universidades-api:
    container_name: universidades-api
    build:
      context: .
      dockerfile: UniversidadesAPI/Dockerfile
    ports: 
      - 8001:80
      - 8002:443
    environment: 
      - connectionStrings__DefaultConnection=
    networks:
      - universidades-api-network

networks:
  universidades-api-network:

volumes:
  db-data: