version: '3.4'

services:
  db:
    container_name: app-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=admin123aa1!
    ports:
      - "1450:1433"
    volumes:
      - db-data:/var/opt/mssql/data/

volumes:
  db-data: